### ISSUE TITLE
Loading meshes is broken; missing some base functionality

### ISSUE THREAD

**Issue by hybridherbst** [gradientspace/geometry3UnityDemos#1]
Hey there,

when I try your example of loading the bunny this is what I get:
![image](https://user-images.githubusercontent.com/2693840/36260969-31da117e-1263-11e8-9a12-6c9d4af65e5a.png)

That doesn't look like a bunny :). The sphere generation example does work, and something happens with the interactive reducer, but the mesh is still messed up.

Also, is there a reverse method to DMeshToUnityMesh (UnityMeshToDMesh)?

Addendum: here's the code I'm using, mostly from the example:
```	
void Start () {
        string curPath = Application.dataPath;
        string filePath = Path.Combine(curPath, "..\\sample_files", "bunny_solid.obj");
        startMesh = StandardMeshReader.ReadMesh(filePath);

        // from original example
        MeshTransforms.FlipLeftRightCoordSystems(startMesh);
        MeshTransforms.Translate(startMesh, -startMesh.CachedBounds.Center);
        MeshTransforms.Scale(startMesh, 8.0 / startMesh.CachedBounds.MaxDim);

        // load wireframe shader
        Material wireframeShader = g3UnityUtils.SafeLoadMaterial("wireframe_shader/Wireframe");

        // create initial mesh
        meshGO = g3UnityUtils.CreateMeshGO("start_mesh", startMesh, wireframeShader);
    }

**Comment by rms80** [comment]
Hrm...this is not happening for me, it works fine. I just pushed an update to the latest g3Sharp revision. There is a chance that the problem you are seeing is due to some locale issues that have been resolved. 

Also added code for UnityMeshToDMesh.

**Comment by hybridherbst** [comment]
Haha, I saw you adding commits live 👍 
Unfortunately the same issue with loading meshes through g3Sharp happens, it still looks the same as in the above screenshot,

Loading a Unity mesh works fine though! Thanks for adding that.
![image](https://user-images.githubusercontent.com/2693840/36268365-8a28cf6a-1276-11e8-8d33-51277a5373db.png)

Any other idea about the loading issue? I'd really like to be able to use the powerful loading routines in g3sharp.

**Comment by rms80** [comment]
Could you try using this line to write out startMesh after the ReadMesh line, and attach the resulting obj mesh here?

StandardMeshWriter.WriteMesh("path.obj", startMesh, WriteOptions.Defaults);

**Comment by hybridherbst** [comment]
There you go.
[output.zip](https://github.com/gradientspace/geometry3UnityDemos/files/1728550/output.zip)

```void Start() {
        // find path to sample file
        string curPath = Application.dataPath;
        string filePath = Path.Combine(curPath, Path.Combine("..\\sample_files", "bunny_solid.obj"));

        // load sample file, convert to unity coordinate system, translate and scale to origin
        startMesh = StandardMeshReader.ReadMesh(filePath);
        StandardMeshWriter.WriteMesh(Path.Combine(curPath, Path.Combine("..\\sample_files", "output.obj")), startMesh, WriteOptions.Defaults);
    }

**Comment by rms80** [comment]
Ok, so it looks like on your system the decimal places in the obj are being ignored. the first coordinate is:

v 0.0611133948 16.90344429 22.52701759

but in the file you sent, it is 

v 611133948 1690344429 2252701759

So, the decimal place was lost in the reading. This is almost certainly a locale issue. Are you sure you updated the g3sharp submodule to the latest revision? If you just pulled the latest revision of this repo, most git clients will not automatically update all the submodules. You will need to explicitly update the submodule too. 

If the StandardMeshReader class doesn't have a member variable named "ReadInvariantCulture", then you don't have the latest revision.

If you do have this latest revision...hrm. trouble.

**Comment by hybridherbst** [comment]
I tried on another machine and it works fine now, thanks!
(and that other machine has german locale as well, so 0,05 instead of 0.05)
Will try on the original machine on monday, until then I see this as resolved - thanks a lot!

**Comment by hybridherbst** [comment]
OK, I can confirm that it works on the machine that originally had these issues. Thanks again.
